In [54]:
import pandas as pd
import numpy as np

main_results = pd.read_csv("/home/marc/projects/rna_seq_workflow/results/functional_annotations/wesdi_denovo/wesdi_denovo_combined_annotations.csv")

new_df = main_results[["symbol","log2FoldChange","KEGG_ko"]].set_index("symbol")

reconstruct_df = new_df[["KEGG_ko"]][new_df['KEGG_ko'] != '-'].dropna()

reconstruct_df["KEGG_ko"] = reconstruct_df["KEGG_ko"].str.split(',')

reconstruct_df =reconstruct_df.explode("KEGG_ko")

reconstruct_df.to_csv("wesdi_denovo_reconstruct.tsv", sep="\t")

reconstruct_df

          KEGG_ko
symbol
g3894   ko:K15877
g5559   ko:K05916
g5507   ko:K01176
g10257  ko:K14686
g7093   ko:K05894
...           ...
g7718   ko:K02365
g5271   ko:K17842
g4781   ko:K09425
g4781   ko:K21769
g3593   ko:K15855

[4675 rows x 1 columns]

In [52]:

color_df = new_df[new_df['KEGG_ko'] != '-'].dropna()

color_df['KEGG_ko'] = color_df['KEGG_ko'].str.split(',')

color_df = color_df.explode("KEGG_ko")

# Group by column 'A' and calculate the mean of column 'B'
color_df = color_df.groupby('KEGG_ko', as_index=False).mean()

color_df = color_df.sort_values(by=["log2FoldChange"], ascending=False)

color_df = color_df.set_index("KEGG_ko")

color_df.to_csv("wesdi_denovo_color.csv", sep="\t", header=None)

color_df

           log2FoldChange
KEGG_ko
ko:K15877        3.928201
ko:K01176        2.259591
ko:K05916        1.805180
ko:K01182        1.463261
ko:K05687        1.372371
...                   ...
ko:K02365       -1.022231
ko:K17842       -1.538031
ko:K09425       -1.923677
ko:K21769       -1.923677
ko:K15855       -2.042591

[3249 rows x 1 columns]