In [11]:
import pandas as pd
import numpy as np

main_results = pd.read_csv("/home/nanopore/projects/rna_seq_workflow/results/20240716_FOXY/functional_annotations/MOT_vs_OT_combined_annotations.csv")

new_df = main_results[["symbol","log2FoldChange","KEGG_ko"]].set_index("symbol")

reconstruct_df = new_df[["KEGG_ko"]][new_df['KEGG_ko'] != '-'].dropna()

reconstruct_df["KEGG_ko"] = reconstruct_df["KEGG_ko"].str.split(',')

reconstruct_df =reconstruct_df.explode("KEGG_ko")

reconstruct_df.to_csv("MOT_vs_OT_reconstruct.tsv", sep="\t")

reconstruct_df

              KEGG_ko
symbol
FOXG_12873  ko:K01824
FOXG_17405  ko:K19305
FOXG_08765  ko:K00559
FOXG_07634  ko:K00101
FOXG_02807  ko:K01739
...               ...
FOXG_08080  ko:K01621
FOXG_03104  ko:K00103
FOXG_03104  ko:K00107
FOXG_02459  ko:K16261
FOXG_08771  ko:K17285

[6363 rows x 1 columns]

In [12]:

color_df = new_df[new_df['KEGG_ko'] != '-'].dropna()

color_df['KEGG_ko'] = color_df['KEGG_ko'].str.split(',')

color_df = color_df.explode("KEGG_ko")

# Group by column 'A' and calculate the mean of column 'B'
color_df = color_df.groupby('KEGG_ko', as_index=False).mean()

color_df = color_df.sort_values(by=["log2FoldChange"], ascending=False)

color_df = color_df.set_index("KEGG_ko")

color_df.to_csv("MOT_vs_OT_color.csv", sep="\t", header=None)

color_df

           log2FoldChange
KEGG_ko
ko:K19305        8.163701
ko:K00276        6.891625
ko:K01728        5.892517
ko:K01053        5.849950
ko:K00489        5.830907
...                   ...
ko:K19900       -4.439240
ko:K01621       -5.356162
ko:K00107       -5.819938
ko:K00103       -5.819938
ko:K17285       -8.307242

[3169 rows x 1 columns]